// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.12.4
// source: api/proto/storage.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	StorageService_PutChunk_FullMethodName    = "/storage.StorageService/PutChunk"
	StorageService_GetChunk_FullMethodName    = "/storage.StorageService/GetChunk"
	StorageService_DeleteChunk_FullMethodName = "/storage.StorageService/DeleteChunk"
	StorageService_HealthCheck_FullMethodName = "/storage.StorageService/HealthCheck"
)

// StorageServiceClient is the client API for StorageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StorageServiceClient interface {
	// PutChunk stores a chunk on the storage server using streaming
	PutChunk(ctx context.Context, opts ...grpc.CallOption) (StorageService_PutChunkClient, error)
	// GetChunk retrieves a chunk from the storage server using streaming
	GetChunk(ctx context.Context, in *GetChunkRequest, opts ...grpc.CallOption) (StorageService_GetChunkClient, error)
	// DeleteChunk removes a chunk from the storage server
	DeleteChunk(ctx context.Context, in *DeleteChunkRequest, opts ...grpc.CallOption) (*DeleteChunkResponse, error)
	// HealthCheck returns the health status of the storage server
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
}

type storageServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStorageServiceClient(cc grpc.ClientConnInterface) StorageServiceClient {
	return &storageServiceClient{cc}
}

func (c *storageServiceClient) PutChunk(ctx context.Context, opts ...grpc.CallOption) (StorageService_PutChunkClient, error) {
	stream, err := c.cc.NewStream(ctx, &StorageService_ServiceDesc.Streams[0], StorageService_PutChunk_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &storageServicePutChunkClient{stream}
	return x, nil
}

type StorageService_PutChunkClient interface {
	Send(*PutChunkRequest) error
	CloseAndRecv() (*PutChunkResponse, error)
	grpc.ClientStream
}

type storageServicePutChunkClient struct {
	grpc.ClientStream
}

func (x *storageServicePutChunkClient) Send(m *PutChunkRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *storageServicePutChunkClient) CloseAndRecv() (*PutChunkResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(PutChunkResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *storageServiceClient) GetChunk(ctx context.Context, in *GetChunkRequest, opts ...grpc.CallOption) (StorageService_GetChunkClient, error) {
	stream, err := c.cc.NewStream(ctx, &StorageService_ServiceDesc.Streams[1], StorageService_GetChunk_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &storageServiceGetChunkClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type StorageService_GetChunkClient interface {
	Recv() (*GetChunkResponse, error)
	grpc.ClientStream
}

type storageServiceGetChunkClient struct {
	grpc.ClientStream
}

func (x *storageServiceGetChunkClient) Recv() (*GetChunkResponse, error) {
	m := new(GetChunkResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *storageServiceClient) DeleteChunk(ctx context.Context, in *DeleteChunkRequest, opts ...grpc.CallOption) (*DeleteChunkResponse, error) {
	out := new(DeleteChunkResponse)
	err := c.cc.Invoke(ctx, StorageService_DeleteChunk_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, StorageService_HealthCheck_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StorageServiceServer is the server API for StorageService service.
// All implementations must embed UnimplementedStorageServiceServer
// for forward compatibility
type StorageServiceServer interface {
	// PutChunk stores a chunk on the storage server using streaming
	PutChunk(StorageService_PutChunkServer) error
	// GetChunk retrieves a chunk from the storage server using streaming
	GetChunk(*GetChunkRequest, StorageService_GetChunkServer) error
	// DeleteChunk removes a chunk from the storage server
	DeleteChunk(context.Context, *DeleteChunkRequest) (*DeleteChunkResponse, error)
	// HealthCheck returns the health status of the storage server
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	mustEmbedUnimplementedStorageServiceServer()
}

// UnimplementedStorageServiceServer must be embedded to have forward compatible implementations.
type UnimplementedStorageServiceServer struct {
}

func (UnimplementedStorageServiceServer) PutChunk(StorageService_PutChunkServer) error {
	return status.Errorf(codes.Unimplemented, "method PutChunk not implemented")
}
func (UnimplementedStorageServiceServer) GetChunk(*GetChunkRequest, StorageService_GetChunkServer) error {
	return status.Errorf(codes.Unimplemented, "method GetChunk not implemented")
}
func (UnimplementedStorageServiceServer) DeleteChunk(context.Context, *DeleteChunkRequest) (*DeleteChunkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteChunk not implemented")
}
func (UnimplementedStorageServiceServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedStorageServiceServer) mustEmbedUnimplementedStorageServiceServer() {}

// UnsafeStorageServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StorageServiceServer will
// result in compilation errors.
type UnsafeStorageServiceServer interface {
	mustEmbedUnimplementedStorageServiceServer()
}

func RegisterStorageServiceServer(s grpc.ServiceRegistrar, srv StorageServiceServer) {
	s.RegisterService(&StorageService_ServiceDesc, srv)
}

func _StorageService_PutChunk_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(StorageServiceServer).PutChunk(&storageServicePutChunkServer{stream})
}

type StorageService_PutChunkServer interface {
	SendAndClose(*PutChunkResponse) error
	Recv() (*PutChunkRequest, error)
	grpc.ServerStream
}

type storageServicePutChunkServer struct {
	grpc.ServerStream
}

func (x *storageServicePutChunkServer) SendAndClose(m *PutChunkResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *storageServicePutChunkServer) Recv() (*PutChunkRequest, error) {
	m := new(PutChunkRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _StorageService_GetChunk_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetChunkRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StorageServiceServer).GetChunk(m, &storageServiceGetChunkServer{stream})
}

type StorageService_GetChunkServer interface {
	Send(*GetChunkResponse) error
	grpc.ServerStream
}

type storageServiceGetChunkServer struct {
	grpc.ServerStream
}

func (x *storageServiceGetChunkServer) Send(m *GetChunkResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _StorageService_DeleteChunk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteChunkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).DeleteChunk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_DeleteChunk_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).DeleteChunk(ctx, req.(*DeleteChunkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StorageService_ServiceDesc is the grpc.ServiceDesc for StorageService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StorageService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "storage.StorageService",
	HandlerType: (*StorageServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DeleteChunk",
			Handler:    _StorageService_DeleteChunk_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _StorageService_HealthCheck_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PutChunk",
			Handler:       _StorageService_PutChunk_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "GetChunk",
			Handler:       _StorageService_GetChunk_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/proto/storage.proto",
}
